/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TrackRouteImport } from './routes/track'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalCategoriesRouteImport } from './routes/portal/categories'
import { Route as PortalDeliveryRouteImport } from './routes/portal/delivery'
import { Route as PortalGalleryRouteImport } from './routes/portal/gallery'
import { Route as PortalHeroRouteImport } from './routes/portal/hero'
import { Route as PortalMediaRouteImport } from './routes/portal/media'
import { Route as PortalOrdersRouteImport } from './routes/portal/orders'
import { Route as PortalProductsRouteImport } from './routes/portal/products'
import { Route as PortalRiderRouteImport } from './routes/portal/rider'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalStorefrontRouteImport } from './routes/portal/storefront'
import { Route as PortalUsersRouteImport } from './routes/portal/users'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCategoriesRoute = PortalCategoriesRouteImport.update({
  id: '/portal/categories',
  path: '/portal/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDeliveryRoute = PortalDeliveryRouteImport.update({
  id: '/portal/delivery',
  path: '/portal/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalGalleryRoute = PortalGalleryRouteImport.update({
  id: '/portal/gallery',
  path: '/portal/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalHeroRoute = PortalHeroRouteImport.update({
  id: '/portal/hero',
  path: '/portal/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMediaRoute = PortalMediaRouteImport.update({
  id: '/portal/media',
  path: '/portal/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/portal/orders',
  path: '/portal/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProductsRoute = PortalProductsRouteImport.update({
  id: '/portal/products',
  path: '/portal/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRiderRoute = PortalRiderRouteImport.update({
  id: '/portal/rider',
  path: '/portal/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStorefrontRoute = PortalStorefrontRouteImport.update({
  id: '/portal/storefront',
  path: '/portal/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalUsersRoute = PortalUsersRouteImport.update({
  id: '/portal/users',
  path: '/portal/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catering': typeof CateringRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/track': typeof TrackRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/portal/categories': typeof PortalCategoriesRoute
  '/portal/delivery': typeof PortalDeliveryRoute
  '/portal/gallery': typeof PortalGalleryRoute
  '/portal/hero': typeof PortalHeroRoute
  '/portal/media': typeof PortalMediaRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/rider': typeof PortalRiderRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/storefront': typeof PortalStorefrontRoute
  '/portal/users': typeof PortalUsersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catering': typeof CateringRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/track': typeof TrackRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/portal/categories': typeof PortalCategoriesRoute
  '/portal/delivery': typeof PortalDeliveryRoute
  '/portal/gallery': typeof PortalGalleryRoute
  '/portal/hero': typeof PortalHeroRoute
  '/portal/media': typeof PortalMediaRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/rider': typeof PortalRiderRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/storefront': typeof PortalStorefrontRoute
  '/portal/users': typeof PortalUsersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/portal': typeof PortalIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catering': typeof CateringRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/track': typeof TrackRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/portal/categories': typeof PortalCategoriesRoute
  '/portal/delivery': typeof PortalDeliveryRoute
  '/portal/gallery': typeof PortalGalleryRoute
  '/portal/hero': typeof PortalHeroRoute
  '/portal/media': typeof PortalMediaRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/rider': typeof PortalRiderRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/storefront': typeof PortalStorefrontRoute
  '/portal/users': typeof PortalUsersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/catering'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/orders'
    | '/profile'
    | '/shop'
    | '/testimonials'
    | '/track'
    | '/verify-otp'
    | '/order/$orderNumber'
    | '/portal/categories'
    | '/portal/delivery'
    | '/portal/gallery'
    | '/portal/hero'
    | '/portal/media'
    | '/portal/orders'
    | '/portal/products'
    | '/portal/rider'
    | '/portal/settings'
    | '/portal/storefront'
    | '/portal/users'
    | '/product/$slug'
    | '/portal/'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/catering'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/orders'
    | '/profile'
    | '/shop'
    | '/testimonials'
    | '/track'
    | '/verify-otp'
    | '/order/$orderNumber'
    | '/portal/categories'
    | '/portal/delivery'
    | '/portal/gallery'
    | '/portal/hero'
    | '/portal/media'
    | '/portal/orders'
    | '/portal/products'
    | '/portal/rider'
    | '/portal/settings'
    | '/portal/storefront'
    | '/portal/users'
    | '/product/$slug'
    | '/portal'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/catering'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/orders'
    | '/profile'
    | '/shop'
    | '/testimonials'
    | '/track'
    | '/verify-otp'
    | '/order/$orderNumber'
    | '/portal/categories'
    | '/portal/delivery'
    | '/portal/gallery'
    | '/portal/hero'
    | '/portal/media'
    | '/portal/orders'
    | '/portal/products'
    | '/portal/rider'
    | '/portal/settings'
    | '/portal/storefront'
    | '/portal/users'
    | '/product/$slug'
    | '/portal/'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CateringRoute: typeof CateringRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrackRoute: typeof TrackRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  PortalCategoriesRoute: typeof PortalCategoriesRoute
  PortalDeliveryRoute: typeof PortalDeliveryRoute
  PortalGalleryRoute: typeof PortalGalleryRoute
  PortalHeroRoute: typeof PortalHeroRoute
  PortalMediaRoute: typeof PortalMediaRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalProductsRoute: typeof PortalProductsRoute
  PortalRiderRoute: typeof PortalRiderRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalStorefrontRoute: typeof PortalStorefrontRoute
  PortalUsersRoute: typeof PortalUsersRoute
  ProductSlugRoute: typeof ProductSlugRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/categories': {
      id: '/portal/categories'
      path: '/portal/categories'
      fullPath: '/portal/categories'
      preLoaderRoute: typeof PortalCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/delivery': {
      id: '/portal/delivery'
      path: '/portal/delivery'
      fullPath: '/portal/delivery'
      preLoaderRoute: typeof PortalDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/gallery': {
      id: '/portal/gallery'
      path: '/portal/gallery'
      fullPath: '/portal/gallery'
      preLoaderRoute: typeof PortalGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/hero': {
      id: '/portal/hero'
      path: '/portal/hero'
      fullPath: '/portal/hero'
      preLoaderRoute: typeof PortalHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/media': {
      id: '/portal/media'
      path: '/portal/media'
      fullPath: '/portal/media'
      preLoaderRoute: typeof PortalMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/portal/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/products': {
      id: '/portal/products'
      path: '/portal/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/rider': {
      id: '/portal/rider'
      path: '/portal/rider'
      fullPath: '/portal/rider'
      preLoaderRoute: typeof PortalRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/storefront': {
      id: '/portal/storefront'
      path: '/portal/storefront'
      fullPath: '/portal/storefront'
      preLoaderRoute: typeof PortalStorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/users': {
      id: '/portal/users'
      path: '/portal/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof PortalUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CateringRoute: CateringRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrackRoute: TrackRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  PortalCategoriesRoute: PortalCategoriesRoute,
  PortalDeliveryRoute: PortalDeliveryRoute,
  PortalGalleryRoute: PortalGalleryRoute,
  PortalHeroRoute: PortalHeroRoute,
  PortalMediaRoute: PortalMediaRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalProductsRoute: PortalProductsRoute,
  PortalRiderRoute: PortalRiderRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalStorefrontRoute: PortalStorefrontRoute,
  PortalUsersRoute: PortalUsersRoute,
  ProductSlugRoute: ProductSlugRoute,
  PortalIndexRoute: PortalIndexRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
